<DIV id=navbar>
<UL>                                                                               
<LI><A href="oalevels.php">O & A Levels</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Maths Syllabus D</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Maths P1 & P2</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Stats</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Accounting</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Biology</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Physics</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Chemistry</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Computers</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Ecomomics</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Commerce</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Business Studies</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Government & Politics</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; International Relations</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Urdu</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; English Language</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; English literature</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; Law</A>
<LI><A href="oalevels.php">&nbsp; &nbsp; &nbsp; General Paper</A>
                                                                                
<LI><A href="linguistics.php">Linguistics</A>
<LI><A href="spanish.php">&nbsp; &nbsp; &nbsp; Spanish</A>
<LI><A href="english.php">&nbsp; &nbsp; &nbsp; English</A>
<LI><A href="french.php">&nbsp; &nbsp; &nbsp; French</A>
<LI><A href="langmind.php">&nbsp; &nbsp; &nbsp; Language & Mind</A>
                                                                                
<LI><A href="testprep.php">Test Preparations</A>
<LI><A href="testprep.php">&nbsp; &nbsp; &nbsp; SAT I</A>
<LI><A href="testprep.php">&nbsp; &nbsp; &nbsp; SAT II subject tests</A>
<LI><A href="testprep.php">&nbsp; &nbsp; &nbsp; GRE</A>
<LI><A href="testprep.php">&nbsp; &nbsp; &nbsp; TOEFL</A>
<LI><A href="testprep.php">&nbsp; &nbsp; &nbsp; IELTS</A>
                                                                                
</div>
