<TABLE width=100% cellSpacing=0 cellPadding=0 align=center border=0 bgcolor="#990000">
  <TR valign=top>
  <td><div id=top><A class=menu0 href="oalevels.php">O & A Levels</A></div></td>
  <td><div id=top><A class=menu0 href="">Linguistics</A></div></td>
  <td><div id=top><A class=menu0 href="">Test Preparations</A></div></td>
  <td><div id=top><A class=menu0 href="/faculty">Faculty</A> </div></td>
  <td><div id=top><A class=menu0 href="courses.php">Course Pages</A></div></td>
  <td><div id=top><A class=menu0 href="">Facilities</A></div></td>
  <td><div id=top><A class=menu0 href="">Events</A></div></td>
  <td><div id=top><A class=menu0 href="register.php">Register Online</A></div></td>
  <td><div id=top><A class=menu0 href="">Fee Schedule</A></div></td>
  <td><div id=top><A class=menu0 href="contact.php">Contact Us</A></div></td>
  <td><div id=top><A class=menu0 href="">Access Webmail</A></div></td>
 <td><div id=top><A class=menu0 href="">About Presage</A></div></td>
</tr></table>
                                                                                
<table width=100% border=0><tr valign=bottom><td width=25%>
<a href="index.php"><img align=left src="logo.gif" border=0></a>
</td><td><div id=BRR><center><b>P R E S A G E &nbsp; T U I T I O N S</div></td><td width=25%>
<div id=login>
<form action=login.php method=post>
        User ID:
        <INPUT size=8 name=userid><br>
        Password:
        <INPUT type=password size=8 name=password><br>
        <INPUT type=submit value=Login></form>
</div>
</td></tr></table>

